=== ljca/mybackup/src_note/develop/others/java_src/Test/Test/WebRoot/WEB-INF/dtd-xml/test.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT tmps (tmp*,stu*)>
<!ELEMENT tmp (year)>
<!ELEMENT year (#PCDATA)>
<!--<!ELEMENT id (#PCDATA)> <!ELEMENT name (#PCDATA)>-->

<!ELEMENT stu (id,name,age,sex,address,tel)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT tel (#PCDATA)>

=== ljca/mybackup/src_note/develop/others/java_src/Test/Test/WebRoot/WEB-INF/dtd-xml/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tmps SYSTEM "test.dtd">
<tmps>
	<tmp>
		<year>未知年份</year>
	</tmp>
	<stu>
		<id>y2ls</id>
		<name>tmp</name>
		<age>22</age>
		<sex>男</sex>
		<address>未知通讯地址</address>
		<tel>未知联系方式</tel>
	</stu>
	 <stu>
    <id>test</id>
    <name>test</name>
    <age>22</age>
    <sex>女</sex>
    <address>未知通讯地址</address>
    <tel>未知联系方式</tel>
  </stu>
</tmps>
